/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManageTheBusiness;

import TheBusiness.Business.Business;
import TheBusiness.ProductManagement.ProductSummary;
import javax.swing.JPanel;

/**
 *
 * @author kal bugrara
 */
public class ManageBusinessDetail1 extends javax.swing.JPanel {

    /**
     * Creates new form ManageSuppliersJPanel
     */
    JPanel CardSequencePanel;

    Business business;

    public ManageBusinessDetail1(Business bz, JPanel jp) {

        CardSequencePanel = jp;
        this.business = bz;
        initComponents();


    }

    public void refreshTable() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
           // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
           private void initComponents() {

                      Back = new javax.swing.JButton();
                      jLabel2 = new javax.swing.JLabel();

                      setBackground(new java.awt.Color(0, 153, 204));
                      setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                      Back.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
                      Back.setText("<< Back");
                      Back.addActionListener(new java.awt.event.ActionListener() {
                                 public void actionPerformed(java.awt.event.ActionEvent evt) {
                                            BackActionPerformed(evt);
                                 }
                      });
                      add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

                      jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
                      jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                      jLabel2.setText("BUSINESS PERFORMANCE DETAILS");
                      add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 800, 40));
           }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        CardSequencePanel.remove(this);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);


    }//GEN-LAST:event_BackActionPerformed


           // Variables declaration - do not modify//GEN-BEGIN:variables
           private javax.swing.JButton Back;
           private javax.swing.JLabel jLabel2;
           // End of variables declaration//GEN-END:variables

}
