/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * WorkAreaJPanel.java
 *
 * Created on May 17, 2020, 8:35:29 AM
 */
package UserInterface.Main.WorkSpaceProfiles;

import TheBusiness.Business.Business;
import TheBusiness.CustomerManagement.CustomerProfile;
import TheBusiness.SalesManagement.SalesPersonProfile;
import UserInterface.Main.WorkSpaceProfiles.OrderManagement.ManageSalesPersonOrders;
import UserInterface.Main.WorkSpaceProfiles.OrderManagement.ProcessOrder;
import javax.swing.JPanel;

/**
 *
 * @author kal
 */
public class SalesPersonWorkAreaJPanel extends javax.swing.JPanel {

    javax.swing.JPanel CardSequencePanel;
    Business business;
    SalesPersonProfile salesperson;

    /**
     * Creates new form UnitRiskWorkArea
     * @param b
     * @param spp
     * @param clp
     */

    public SalesPersonWorkAreaJPanel(Business b, SalesPersonProfile spp, JPanel clp) {

        business = b;
        this.CardSequencePanel = clp;
        salesperson = spp;
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
           // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
           private void initComponents() {

                      jButton4 = new javax.swing.JButton();
                      jButton9 = new javax.swing.JButton();
                      jButton10 = new javax.swing.JButton();
                      jButton8 = new javax.swing.JButton();
                      jButton11 = new javax.swing.JButton();
                      customerNameTextField = new javax.swing.JTextField();
                      jLabel1 = new javax.swing.JLabel();

                      setForeground(new java.awt.Color(51, 51, 51));

                      jButton4.setBackground(new java.awt.Color(0, 102, 153));
                      jButton4.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
                      jButton4.setForeground(new java.awt.Color(255, 255, 255));
                      jButton4.setText("Serve Customers");
                      jButton4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
                      jButton4.setMaximumSize(new java.awt.Dimension(200, 40));
                      jButton4.setMinimumSize(new java.awt.Dimension(20, 23));
                      jButton4.setPreferredSize(new java.awt.Dimension(240, 30));
                      jButton4.addActionListener(new java.awt.event.ActionListener() {
                                 public void actionPerformed(java.awt.event.ActionEvent evt) {
                                            jButton4IdentifyResourceAssetsActionPerformed(evt);
                                 }
                      });

                      jButton9.setBackground(new java.awt.Color(0, 102, 153));
                      jButton9.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
                      jButton9.setForeground(new java.awt.Color(255, 255, 255));
                      jButton9.setText("Manage Profile");
                      jButton9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
                      jButton9.setMaximumSize(new java.awt.Dimension(200, 40));
                      jButton9.setMinimumSize(new java.awt.Dimension(20, 20));
                      jButton9.setPreferredSize(new java.awt.Dimension(240, 25));
                      jButton9.addActionListener(new java.awt.event.ActionListener() {
                                 public void actionPerformed(java.awt.event.ActionEvent evt) {
                                            jButton9ActionPerformed(evt);
                                 }
                      });

                      jButton10.setBackground(new java.awt.Color(0, 102, 153));
                      jButton10.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
                      jButton10.setForeground(new java.awt.Color(255, 255, 255));
                      jButton10.setText("Review Order Status History");
                      jButton10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
                      jButton10.setMaximumSize(new java.awt.Dimension(200, 40));
                      jButton10.setMinimumSize(new java.awt.Dimension(20, 20));
                      jButton10.setPreferredSize(new java.awt.Dimension(240, 25));
                      jButton10.addActionListener(new java.awt.event.ActionListener() {
                                 public void actionPerformed(java.awt.event.ActionEvent evt) {
                                            jButton10ActionPerformed(evt);
                                 }
                      });

                      jButton8.setBackground(new java.awt.Color(0, 102, 153));
                      jButton8.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
                      jButton8.setForeground(new java.awt.Color(255, 255, 255));
                      jButton8.setText("Review Comission");
                      jButton8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
                      jButton8.setMaximumSize(new java.awt.Dimension(200, 40));
                      jButton8.setMinimumSize(new java.awt.Dimension(20, 20));
                      jButton8.setPreferredSize(new java.awt.Dimension(240, 25));
                      jButton8.addActionListener(new java.awt.event.ActionListener() {
                                 public void actionPerformed(java.awt.event.ActionEvent evt) {
                                            jButton8ActionPerformed(evt);
                                 }
                      });

                      jButton11.setBackground(new java.awt.Color(0, 102, 153));
                      jButton11.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
                      jButton11.setForeground(new java.awt.Color(255, 255, 255));
                      jButton11.setText("Performance Reports");
                      jButton11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
                      jButton11.setMaximumSize(new java.awt.Dimension(200, 40));
                      jButton11.setMinimumSize(new java.awt.Dimension(20, 20));
                      jButton11.setPreferredSize(new java.awt.Dimension(240, 25));
                      jButton11.addActionListener(new java.awt.event.ActionListener() {
                                 public void actionPerformed(java.awt.event.ActionEvent evt) {
                                            jButton11ActionPerformed(evt);
                                 }
                      });

                      jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
                      jLabel1.setText("Customer");

                      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                      this.setLayout(layout);
                      layout.setHorizontalGroup(
                                 layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                 .addGroup(layout.createSequentialGroup()
                                            .addGap(22, 22, 22)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                       .addGroup(layout.createSequentialGroup()
                                                                  .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                  .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                       .addComponent(customerNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                       .addGroup(layout.createSequentialGroup()
                                                                  .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                  .addGap(12, 12, 12)
                                                                  .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                  .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                       .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addContainerGap(18, Short.MAX_VALUE))
                      );

                      layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton10, jButton11, jButton4, jButton8, jButton9});

                      layout.setVerticalGroup(
                                 layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                 .addGroup(layout.createSequentialGroup()
                                            .addGap(51, 51, 51)
                                            .addComponent(jLabel1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(customerNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(39, 39, 39)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                       .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                       .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                       .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(61, 61, 61)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                       .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                       .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addContainerGap(291, Short.MAX_VALUE))
                      );

                      layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton10, jButton11, jButton4, jButton8, jButton9});

           }// </editor-fold>//GEN-END:initComponents

    private void jButton4IdentifyResourceAssetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4IdentifyResourceAssetsActionPerformed
        
// TODO add your handling code here:

 
        String customername = customerNameTextField.getText();
        if (customername.isEmpty()) return;
        CustomerProfile selectedcustomer = business.getCustomerDirectory().findCustomer(customername);

        ProcessOrder aos = new ProcessOrder(business, selectedcustomer ,salesperson, CardSequencePanel);

        CardSequencePanel.add("ManageVulns", aos);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);

    }//GEN-LAST:event_jButton4IdentifyResourceAssetsActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:


//        ManageVulns aos = new  ManageVulns(businessunit, CardSequencePanel);
        // aos.setAgenda(businessunit.getRiskManagementAgenda());
//        CardSequencePanel.add("ManageVulns", aos);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);

}//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:

        ManageSalesPersonOrders iet = new ManageSalesPersonOrders(business, CardSequencePanel);

        CardSequencePanel.add("FindResourceAsset", iet);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);

    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:

        CardSequencePanel.removeAll();
        //      ViewBusinessUnitRiskProfile drpd= new ViewBusinessUnitRiskProfile(businessunit, CardSequencePanel);
//        ManageHazards drpd = new ManageHazards(businessunit, CardSequencePanel);
//        CardSequencePanel.add("ManageRiskProfiles", drpd);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
}//GEN-LAST:event_jButton8ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:

        CardSequencePanel.removeAll();
//        ManageIncidents aos = new  ManageIncidents(businessunit, CardSequencePanel);
        // aos.setAgenda(businessunit.getRiskManagementAgenda());
//        CardSequencePanel.add("RiskAgendaObjectives", aos);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
}//GEN-LAST:event_jButton11ActionPerformed


           // Variables declaration - do not modify//GEN-BEGIN:variables
           private javax.swing.JTextField customerNameTextField;
           private javax.swing.JButton jButton10;
           private javax.swing.JButton jButton11;
           private javax.swing.JButton jButton4;
           private javax.swing.JButton jButton8;
           private javax.swing.JButton jButton9;
           private javax.swing.JLabel jLabel1;
           // End of variables declaration//GEN-END:variables

}
