/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManageTheBusiness;

import UserInterface.ProductManagement.*;
import TheBusiness.Business.Business;
import TheBusiness.ProductManagement.Product;
import TheBusiness.Supplier.Supplier;
import javax.swing.JPanel;

/**
 *
 * @author kal bugrara
 */
public class ManageTheBusinessJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageSuppliersJPanel
     */
    JPanel CardSequencePanel;
    Business business;
    Supplier selectedsupplier;
    Product selectedproduct;

    public ManageTheBusinessJPanel(Business bz, JPanel jp) {
        CardSequencePanel = jp;
        this.business = bz;
        initComponents();

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
           // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
           private void initComponents() {

                      Back = new javax.swing.JButton();
                      Next = new javax.swing.JButton();
                      jLabel1 = new javax.swing.JLabel();
                      jLabel2 = new javax.swing.JLabel();

                      setBackground(new java.awt.Color(0, 153, 153));
                      setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                      Back.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
                      Back.setText("<< Back");
                      Back.addActionListener(new java.awt.event.ActionListener() {
                                 public void actionPerformed(java.awt.event.ActionEvent evt) {
                                            BackActionPerformed(evt);
                                 }
                      });
                      add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 120, -1));

                      Next.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
                      Next.setText("Next >>");
                      Next.addActionListener(new java.awt.event.ActionListener() {
                                 public void actionPerformed(java.awt.event.ActionEvent evt) {
                                            NextActionPerformed(evt);
                                 }
                      });
                      add(Next, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 260, 120, -1));

                      jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
                      jLabel1.setText("Business Name");
                      add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 190, -1));

                      jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
                      jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                      jLabel2.setText("MANAGE THE BUSINESS");
                      add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 800, -1));
           }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        CardSequencePanel.remove(this);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);

    }//GEN-LAST:event_BackActionPerformed

    private void NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextActionPerformed
        // TODO add your handling code here:
        
        ManageBusinessDetail1 mppd = new ManageBusinessDetail1(business, CardSequencePanel);
        CardSequencePanel.add(mppd);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);

    }//GEN-LAST:event_NextActionPerformed


           // Variables declaration - do not modify//GEN-BEGIN:variables
           private javax.swing.JButton Back;
           private javax.swing.JButton Next;
           private javax.swing.JLabel jLabel1;
           private javax.swing.JLabel jLabel2;
           // End of variables declaration//GEN-END:variables

}
